# Generated by Django 4.1 on 2024-10-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('services_needed', models.CharField(choices=[('design', 'Web Design'), ('development', 'Web Development'), ('seo', 'SEO Optimization'), ('ecommerce', 'E-commerce Solution'), ('maintenance', 'Website Maintenance'), ('other', 'Other')], max_length=255)),
                ('project_description', models.TextField()),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('timeline', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
